### ISSUE TITLE
Proposition ajout de paramètres

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/schema-lieux-covoiturage#4]
J'ouvre cette issue pour le compte de @GabrielPlassat. Voir #2.

---
Propositions d'ajout de paramètre pour décrire une aire/lieu de covoiturage :

- stationnement vélo ouvert type arceau
- stationnement vélo fermé type box
- borne charge VE: type, nombre, ...
- connexion au transport public: distance à l'arrêt de bus/train le plus proche

**Comment by AntoineAugusti** [comment]
Je reprends ce qu'on avait dit en réunion. @johanricher et @ishanb, n'hésitez pas à compléter.

Nous avons choisi dans un premier temps de ne pas faire apparaître de telles informations. Certaines données sont collectées ailleurs : bornes véhicules électriques et transports public par exemple. L'idée est de croiser ces données avec les lieux de covoiturage pour avoir une version augmentée. Inutile de refaire le travail initié là-bas.

Pour les autres commodités, il a été choisi de les noter en commentaires pour le moment. Voir colonne `comm` :
> Commentaires éventuels sur les commodités mises à disposition du grand public comme : le numéro de téléphone unique qui indique les services disponibles au moment de l’arrivée sur l’aire pour réaliser le dernier kilomètre ; la présence de prises 220V ou USB ; accès à du réseau (télécom, WiFi) ; sanitaires ; intermodalité en transports

https://schema.data.gouv.fr/etalab/schema-lieux-covoiturage/latest/documentation.html

**Comment by IshanB** [comment]
En effet

Le but de ce travail était de simplifier au maximum la description des lieux de covoiturage par les collectivités.

Intégrer des données relatives à d'autres modes de transport (irve, stationnement vélo par ex) a été finalement considéré comme superflu car d'autres bases de données existent ou sont en cours de construction. Il vaut mieux conserver 1 seule base de référence par mode de transport, notamment pour faciliter la mise à jour de ces bases (les collectivités ne devraient pas à avoir à effectuer une modif sur un stationnement vélo dans plusieurs bases différentes).

Les différentes bases peuvent tout à fait être combinées par un service de mobilité comme une application de covoiturage.

**Comment by AntoineAugusti** [comment]
En l'absence de commentaires je clos la discussion.
