### ISSUE TITLE
Validata bug sur un SIREN pourtant valide

### ISSUE THREAD

**Issue by IshanB** [etalab/schema-lieux-covoiturage#6]
Bug obtenu en essayant de valider un fichier consolidé de points de rencontre en covoiturage.
Le siren 244200895 ne passe pas le validateur alors qu'il existe bien (https://entreprise.data.gouv.fr/etablissement/244200895).

![image](https://user-images.githubusercontent.com/28890473/64198397-7082b880-ce88-11e9-86b0-3514b3cf008f.png)

**Comment by AntoineAugusti** [comment]
Hello,

Je viens de tester avec [un CSV minimal](https://gist.github.com/AntoineAugusti/224bf77bb4666b58a48149b7c49c9852) reprenant ton SIREN et celui-ci passe bien [la validation](https://validata.etalab.studio/table-schema?input=url&schema_name=schema-datagouv-fr.etalab%2Fschema-lieux-covoiturage&schema_ref=&url=https%3A%2F%2Fgist.githubusercontent.com%2FAntoineAugusti%2F224bf77bb4666b58a48149b7c49c9852%2Fraw%2Feb0249e5df18f2c7f5fec65eb86296a21c378529%2Ftest-covoiturage-issue-6.csv).

Dans ta capture d'écran il me semble que ta première colonne est invalide : on voit le numéro 1 avant la colonne `id_lieu`. Arrives-tu à reproduire ?

**Comment by IshanB** [comment]
Hello
Désolé, je n'ai eu le temps de m'y remettre qu'aujourd'hui.
C'est bon, le champ était en "Texte" sur Excel, il s'agissait d'un simple problème de format.
C'est corrigé et le validateur passe.
merci
